<a href="https://colab.research.google.com/github/rishabh7302/Pytorch/blob/main/dataset_and_dataloader_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [170]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [171]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [172]:
df.shape

(569, 33)

In [173]:
df["diagnosis"].unique()

array(['M', 'B'], dtype=object)

In [174]:
df["diagnosis"].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [175]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [176]:
df.head()

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

# Train test split

In [177]:
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [178]:
type(x_train)

pandas.core.frame.DataFrame

In [179]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [180]:
type(x_train)

numpy.ndarray

In [181]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [182]:
type(y_train)

numpy.ndarray

In [183]:
x_train_tensor=torch.from_numpy(x_train.astype(np.float32))
x_test_tensor=torch.from_numpy(x_test.astype(np.float32))
y_train_tensor=torch.from_numpy(y_train.astype(np.float32))
y_test_tensor=torch.from_numpy(y_test.astype(np.float32))

In [184]:
x_train_tensor.shape

torch.Size([455, 30])

In [185]:
from torch.utils.data import Dataset,DataLoader

class CustomDataset(Dataset):

  def __init__(self,features,labels):
    self.features=features
    self.labels=labels

  def __len__(self):
    return len(self.features)

  def get_lengths(self):
    return len(self.features), len(self.labels)

  def __getitem__(self,idx):
    return self.features[idx],self.labels[idx]

In [186]:
train_dataset=CustomDataset(x_train_tensor,y_train_tensor)
test_dataset=CustomDataset(x_test_tensor,y_test_tensor)

In [187]:
print(train_dataset.get_lengths())

(455, 455)

In [188]:
train_loader=DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=32,shuffle=True)

In [189]:
for X, y in train_loader:
   print(X.shape, y.shape)

torch.Size([32, 30]) torch.Size([32])
torch.Size([32, 30]) torch.Size([32])
torch.Size([32, 30]) torch.Size([32])
torch.Size([32, 30]) torch.Size([32])
torch.Size([32, 30]) torch.Size([32])
torch.Size([32, 30]) torch.Size([32])
torch.Size([32, 30]) torch.Size([32])
torch.Size([32, 30]) torch.Size([32])
torch.Size([32, 30]) torch.Size([32])
torch.Size([32, 30]) torch.Size([32])
torch.Size([32, 30]) torch.Size([32])
torch.Size([32, 30]) torch.Size([32])
torch.Size([32, 30]) torch.Size([32])
torch.Size([32, 30]) torch.Size([32])
torch.Size([7, 30]) torch.Size([7])

# Defining the model

In [190]:
import torch.nn as nn

class MySimpleNN(nn.Module):

    def __init__(self,num_features):
      super().__init__()
      self.linear=nn.Linear(num_features,1)
      self.sigmoid=nn.Sigmoid()

    def forward(self,features):
      out=self.linear(features)
      out=self.sigmoid(out)
      return out

# important parameters

In [191]:
learning_rate=0.1
epochs=25

In [192]:
model=MySimpleNN(x_train_tensor.shape[1])
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)
loss_function=nn.BCELoss()

# Training Pipeline

In [193]:
# define loop

for epoch in range(epochs):

  for batch_feature,batch_labels in train_loader:

    # forward pass
    y_pred=model(batch_feature)

    # loss function
    loss=loss_function(y_pred,batch_labels.view(-1,1))

    # clear gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    #parameters update
    optimizer.step()

    # print loss in each epoch

    print(f"Epoch:{epoch+1},Loss:{loss.item()}")

Epoch:1,Loss:1.0080177783966064
Epoch:1,Loss:0.6963179707527161
Epoch:1,Loss:0.6024502515792847
Epoch:1,Loss:0.43501728773117065
Epoch:1,Loss:0.3790161609649658
Epoch:1,Loss:0.337796688079834
Epoch:1,Loss:0.35045358538627625
Epoch:1,Loss:0.32677263021469116
Epoch:1,Loss:0.34258246421813965
Epoch:1,Loss:0.23522019386291504
Epoch:1,Loss:0.17868249118328094
Epoch:1,Loss:0.29104605317115784
Epoch:1,Loss:0.228847473859787
Epoch:1,Loss:0.2515130639076233
Epoch:1,Loss:0.49557676911354065
Epoch:2,Loss:0.21167311072349548
Epoch:2,Loss:0.13859052956104279
Epoch:2,Loss:0.21792072057724
Epoch:2,Loss:0.19046716392040253
Epoch:2,Loss:0.18401625752449036
Epoch:2,Loss:0.2604752480983734
Epoch:2,Loss:0.21001656353473663
Epoch:2,Loss:0.22304347157478333
Epoch:2,Loss:0.25606146454811096
Epoch:2,Loss:0.21072521805763245
Epoch:2,Loss:0.09696125984191895
Epoch:2,Loss:0.2139427363872528
Epoch:2,Loss:0.1778746396303177
Epoch:2,Loss:0.1519174575805664
Epoch:2,Loss:0.24445700645446777
Epoch:3,Loss:0.12126659601926804
Epoch:3,Loss:0.24228700995445251
Epoch:3,Loss:0.20803998410701752
Epoch:3,Loss:0.16186760365962982
Epoch:3,Loss:0.12814225256443024
Epoch:3,Loss:0.17204883694648743
Epoch:3,Loss:0.1669221818447113
Epoch:3,Loss:0.1159786656498909
Epoch:3,Loss:0.13785016536712646
Epoch:3,Loss:0.16779214143753052
Epoch:3,Loss:0.12582848966121674
Epoch:3,Loss:0.15957990288734436
Epoch:3,Loss:0.1354314684867859
Epoch:3,Loss:0.1876852810382843
Epoch:3,Loss:0.1364673227071762
Epoch:4,Loss:0.08734000474214554
Epoch:4,Loss:0.17297843098640442
Epoch:4,Loss:0.09722673147916794
Epoch:4,Loss:0.11955349892377853
Epoch:4,Loss:0.2554766535758972
Epoch:4,Loss:0.09359263628721237
Epoch:4,Loss:0.14277255535125732
Epoch:4,Loss:0.1725277304649353
Epoch:4,Loss:0.168204665184021
Epoch:4,Loss:0.14755405485630035
Epoch:4,Loss:0.15382903814315796
Epoch:4,Loss:0.10934854298830032
Epoch:4,Loss:0.1079188659787178
Epoch:4,Loss:0.11545737832784653
Epoch:4,Loss:0.19251933693885803
Epoch:5,Loss:0.09819138050079346
Epoch:5,Loss:0.12177735567092896
Epoch:5,Loss:0.1358771175146103
Epoch:5,Loss:0.1185048446059227
Epoch:5,Loss:0.23676465451717377
Epoch:5,Loss:0.11885330826044083
Epoch:5,Loss:0.12735114991664886
Epoch:5,Loss:0.21469372510910034
Epoch:5,Loss:0.0902765616774559
Epoch:5,Loss:0.16020773351192474
Epoch:5,Loss:0.13721100986003876
Epoch:5,Loss:0.09577269852161407
Epoch:5,Loss:0.06866628676652908
Epoch:5,Loss:0.060614362359046936
Epoch:5,Loss:0.16387464106082916
Epoch:6,Loss:0.06680361181497574
Epoch:6,Loss:0.09840838611125946
Epoch:6,Loss:0.11050692200660706
Epoch:6,Loss:0.14725042879581451
Epoch:6,Loss:0.15122653543949127
Epoch:6,Loss:0.08533264696598053
Epoch:6,Loss:0.09236076474189758
Epoch:6,Loss:0.18688467144966125
Epoch:6,Loss:0.07888352870941162
Epoch:6,Loss:0.11308283358812332
Epoch:6,Loss:0.1850830465555191
Epoch:6,Loss:0.14949578046798706
Epoch:6,Loss:0.09197477996349335
Epoch:6,Loss:0.11961255967617035
Epoch:6,Loss:0.12928220629692078
Epoch:7,Loss:0.20541444420814514
Epoch:7,Loss:0.12751233577728271
Epoch:7,Loss:0.11332812160253525
Epoch:7,Loss:0.20163008570671082
Epoch:7,Loss:0.09887450188398361
Epoch:7,Loss:0.12025096267461777
Epoch:7,Loss:0.08600697666406631
Epoch:7,Loss:0.10504572838544846
Epoch:7,Loss:0.09495185315608978
Epoch:7,Loss:0.08764903992414474
Epoch:7,Loss:0.08339565247297287
Epoch:7,Loss:0.07408362627029419
Epoch:7,Loss:0.07539138197898865
Epoch:7,Loss:0.10957647114992142
Epoch:7,Loss:0.15854796767234802
Epoch:8,Loss:0.19195954501628876
Epoch:8,Loss:0.08898726850748062
Epoch:8,Loss:0.10698582231998444
Epoch:8,Loss:0.08205218613147736
Epoch:8,Loss:0.09579477459192276
Epoch:8,Loss:0.04706712067127228
Epoch:8,Loss:0.10697057098150253
Epoch:8,Loss:0.135239839553833
Epoch:8,Loss:0.17744305729866028
Epoch:8,Loss:0.10743105411529541
Epoch:8,Loss:0.12640318274497986
Epoch:8,Loss:0.10407623648643494
Epoch:8,Loss:0.08673333376646042
Epoch:8,Loss:0.06035115569829941
Epoch:8,Loss:0.16961126029491425
Epoch:9,Loss:0.09030333161354065
Epoch:9,Loss:0.23503944277763367
Epoch:9,Loss:0.06528903543949127
Epoch:9,Loss:0.08543357253074646
Epoch:9,Loss:0.08335500210523605
Epoch:9,Loss:0.21753475069999695
Epoch:9,Loss:0.06230872869491577
Epoch:9,Loss:0.09090985357761383
Epoch:9,Loss:0.1367907077074051
Epoch:9,Loss:0.07664673030376434
Epoch:9,Loss:0.09121893346309662
Epoch:9,Loss:0.02284122444689274
Epoch:9,Loss:0.13494199514389038
Epoch:9,Loss:0.10184047371149063
Epoch:9,Loss:0.013922027312219143
Epoch:10,Loss:0.09756287932395935
Epoch:10,Loss:0.14409999549388885
Epoch:10,Loss:0.037558045238256454
Epoch:10,Loss:0.06987761706113815
Epoch:10,Loss:0.10853365808725357
Epoch:10,Loss:0.1387123018503189
Epoch:10,Loss:0.06473348289728165
Epoch:10,Loss:0.13731448352336884
Epoch:10,Loss:0.10496114194393158
Epoch:10,Loss:0.1736166775226593
Epoch:10,Loss:0.06646853685379028
Epoch:10,Loss:0.04776693880558014
Epoch:10,Loss:0.10493440181016922
Epoch:10,Loss:0.15455865859985352
Epoch:10,Loss:0.017213068902492523
Epoch:11,Loss:0.06705901771783829
Epoch:11,Loss:0.07513430714607239
Epoch:11,Loss:0.13426339626312256
Epoch:11,Loss:0.12243060767650604
Epoch:11,Loss:0.05152512341737747
Epoch:11,Loss:0.0750226229429245
Epoch:11,Loss:0.1340375691652298
Epoch:11,Loss:0.11529617011547089
Epoch:11,Loss:0.06695932894945145
Epoch:11,Loss:0.14262934029102325
Epoch:11,Loss:0.1994829922914505
Epoch:11,Loss:0.059447284787893295
Epoch:11,Loss:0.04134851694107056
Epoch:11,Loss:0.11857793480157852
Epoch:11,Loss:0.06731478869915009
Epoch:12,Loss:0.042840879410505295
Epoch:12,Loss:0.08826237171888351
Epoch:12,Loss:0.0981726199388504
Epoch:12,Loss:0.11430633813142776
Epoch:12,Loss:0.03105008974671364
Epoch:12,Loss:0.09866293519735336
Epoch:12,Loss:0.07088861614465714
Epoch:12,Loss:0.14509373903274536
Epoch:12,Loss:0.24815325438976288
Epoch:12,Loss:0.09546002000570297
Epoch:12,Loss:0.11589963734149933
Epoch:12,Loss:0.10641003400087357
Epoch:12,Loss:0.06639695912599564
Epoch:12,Loss:0.04472262039780617
Epoch:12,Loss:0.09115475416183472
Epoch:13,Loss:0.12148971855640411
Epoch:13,Loss:0.04631975293159485
Epoch:13,Loss:0.05537467449903488
Epoch:13,Loss:0.11585649102926254
Epoch:13,Loss:0.059907231479883194
Epoch:13,Loss:0.21060818433761597
Epoch:13,Loss:0.06056978181004524
Epoch:13,Loss:0.07375305891036987
Epoch:13,Loss:0.051240839064121246
Epoch:13,Loss:0.05688602104783058
Epoch:13,Loss:0.16398651897907257
Epoch:13,Loss:0.09879247099161148
Epoch:13,Loss:0.2115517258644104
Epoch:13,Loss:0.025650542229413986
Epoch:13,Loss:0.03313615545630455
Epoch:14,Loss:0.076459601521492
Epoch:14,Loss:0.14500434696674347
Epoch:14,Loss:0.021735431626439095
Epoch:14,Loss:0.08955308049917221
Epoch:14,Loss:0.12638099491596222
Epoch:14,Loss:0.03259938582777977
Epoch:14,Loss:0.08502030372619629
Epoch:14,Loss:0.06318662315607071
Epoch:14,Loss:0.06186993047595024
Epoch:14,Loss:0.16239625215530396
Epoch:14,Loss:0.18210230767726898
Epoch:14,Loss:0.08421654999256134
Epoch:14,Loss:0.03681838512420654
Epoch:14,Loss:0.16307435929775238
Epoch:14,Loss:0.005678080953657627
Epoch:15,Loss:0.0650770366191864
Epoch:15,Loss:0.0876503512263298
Epoch:15,Loss:0.13809815049171448
Epoch:15,Loss:0.06762931495904922
Epoch:15,Loss:0.05881884694099426
Epoch:15,Loss:0.02593115344643593
Epoch:15,Loss:0.043553706258535385
Epoch:15,Loss:0.12021581828594208
Epoch:15,Loss:0.05976872891187668
Epoch:15,Loss:0.2208220362663269
Epoch:15,Loss:0.07310258597135544
Epoch:15,Loss:0.051055215299129486
Epoch:15,Loss:0.1815665364265442
Epoch:15,Loss:0.11104799807071686
Epoch:15,Loss:0.023156331852078438
Epoch:16,Loss:0.10047672688961029
Epoch:16,Loss:0.05894060432910919
Epoch:16,Loss:0.14242291450500488
Epoch:16,Loss:0.04362551495432854
Epoch:16,Loss:0.050609420984983444
Epoch:16,Loss:0.09312904626131058
Epoch:16,Loss:0.06650958210229874
Epoch:16,Loss:0.09604810178279877
Epoch:16,Loss:0.05583327263593674
Epoch:16,Loss:0.0824628621339798
Epoch:16,Loss:0.03260813653469086
Epoch:16,Loss:0.10067342966794968
Epoch:16,Loss:0.08926757425069809
Epoch:16,Loss:0.24996313452720642
Epoch:16,Loss:0.12293333560228348
Epoch:17,Loss:0.21491290628910065
Epoch:17,Loss:0.026797538623213768
Epoch:17,Loss:0.09540194272994995
Epoch:17,Loss:0.1186467856168747
Epoch:17,Loss:0.13565364480018616
Epoch:17,Loss:0.07614211738109589
Epoch:17,Loss:0.1446615308523178
Epoch:17,Loss:0.0777253806591034
Epoch:17,Loss:0.08227211982011795
Epoch:17,Loss:0.04219048470258713
Epoch:17,Loss:0.04736584424972534
Epoch:17,Loss:0.07393290847539902
Epoch:17,Loss:0.08571167290210724
Epoch:17,Loss:0.036589257419109344
Epoch:17,Loss:0.04863499850034714
Epoch:18,Loss:0.12255626916885376
Epoch:18,Loss:0.20227256417274475
Epoch:18,Loss:0.08960213512182236
Epoch:18,Loss:0.11153455078601837
Epoch:18,Loss:0.05277663841843605
Epoch:18,Loss:0.03589082881808281
Epoch:18,Loss:0.0938277319073677
Epoch:18,Loss:0.030843455344438553
Epoch:18,Loss:0.05689886212348938
Epoch:18,Loss:0.12319471687078476
Epoch:18,Loss:0.06230388954281807
Epoch:18,Loss:0.02857961319386959
Epoch:18,Loss:0.06404897570610046
Epoch:18,Loss:0.16757740080356598
Epoch:18,Loss:0.05322878807783127
Epoch:19,Loss:0.043530140072107315
Epoch:19,Loss:0.08522157371044159
Epoch:19,Loss:0.2839694321155548
Epoch:19,Loss:0.10957267880439758
Epoch:19,Loss:0.07009667158126831
Epoch:19,Loss:0.05142167583107948
Epoch:19,Loss:0.07757788896560669
Epoch:19,Loss:0.039606884121894836
Epoch:19,Loss:0.04951637610793114
Epoch:19,Loss:0.07395482063293457
Epoch:19,Loss:0.10339204967021942
Epoch:19,Loss:0.10778050869703293
Epoch:19,Loss:0.07538427412509918
Epoch:19,Loss:0.037530865520238876
Epoch:19,Loss:0.13086234033107758
Epoch:20,Loss:0.1344587206840515
Epoch:20,Loss:0.05272071063518524
Epoch:20,Loss:0.06248809024691582
Epoch:20,Loss:0.08123072236776352
Epoch:20,Loss:0.04574316740036011
Epoch:20,Loss:0.04839881882071495
Epoch:20,Loss:0.10244116932153702
Epoch:20,Loss:0.024195168167352676
Epoch:20,Loss:0.04410054534673691
Epoch:20,Loss:0.14769388735294342
Epoch:20,Loss:0.07506806403398514
Epoch:20,Loss:0.09791363030672073
Epoch:20,Loss:0.03919784724712372
Epoch:20,Loss:0.09431536495685577
Epoch:20,Loss:0.7841667532920837
Epoch:21,Loss:0.13059060275554657
Epoch:21,Loss:0.059975072741508484
Epoch:21,Loss:0.08160951733589172
Epoch:21,Loss:0.057519279420375824
Epoch:21,Loss:0.2088560312986374
Epoch:21,Loss:0.05805172771215439
Epoch:21,Loss:0.048091910779476166
Epoch:21,Loss:0.10965655744075775
Epoch:21,Loss:0.0786224976181984
Epoch:21,Loss:0.06773141771554947
Epoch:21,Loss:0.021951045840978622
Epoch:21,Loss:0.120557501912117
Epoch:21,Loss:0.05525368079543114
Epoch:21,Loss:0.11177223920822144
Epoch:21,Loss:0.010007343254983425
Epoch:22,Loss:0.05104262754321098
Epoch:22,Loss:0.035002194344997406
Epoch:22,Loss:0.17751146852970123
Epoch:22,Loss:0.06985491514205933
Epoch:22,Loss:0.1293138563632965
Epoch:22,Loss:0.07824032753705978
Epoch:22,Loss:0.06150946766138077
Epoch:22,Loss:0.05037673935294151
Epoch:22,Loss:0.04251521825790405
Epoch:22,Loss:0.13155318796634674
Epoch:22,Loss:0.04817412793636322
Epoch:22,Loss:0.10038341581821442
Epoch:22,Loss:0.08417396992444992
Epoch:22,Loss:0.13374871015548706
Epoch:22,Loss:0.032111477106809616
Epoch:23,Loss:0.06705238670110703
Epoch:23,Loss:0.12052848935127258
Epoch:23,Loss:0.10276059806346893
Epoch:23,Loss:0.06099637225270271
Epoch:23,Loss:0.06839906424283981
Epoch:23,Loss:0.20792998373508453
Epoch:23,Loss:0.04627213627099991
Epoch:23,Loss:0.06555238366127014
Epoch:23,Loss:0.07813873887062073
Epoch:23,Loss:0.0960058718919754
Epoch:23,Loss:0.03445226699113846
Epoch:23,Loss:0.05012403801083565
Epoch:23,Loss:0.08893664181232452
Epoch:23,Loss:0.07186692953109741
Epoch:23,Loss:0.14021985232830048
Epoch:24,Loss:0.07452187687158585
Epoch:24,Loss:0.1198934018611908
Epoch:24,Loss:0.07480008900165558
Epoch:24,Loss:0.19961589574813843
Epoch:24,Loss:0.0420733243227005
Epoch:24,Loss:0.05878680944442749
Epoch:24,Loss:0.06013423204421997
Epoch:24,Loss:0.05065115541219711
Epoch:24,Loss:0.04250996932387352
Epoch:24,Loss:0.1070622056722641
Epoch:24,Loss:0.12567433714866638
Epoch:24,Loss:0.07124342024326324
Epoch:24,Loss:0.08353697508573532
Epoch:24,Loss:0.036354534327983856
Epoch:24,Loss:0.14486192166805267
Epoch:25,Loss:0.022666579112410545
Epoch:25,Loss:0.06048984453082085
Epoch:25,Loss:0.13806453347206116
Epoch:25,Loss:0.30669501423835754
Epoch:25,Loss:0.06410583853721619
Epoch:25,Loss:0.1015554666519165
Epoch:25,Loss:0.03488927334547043
Epoch:25,Loss:0.034123148769140244
Epoch:25,Loss:0.08650590479373932
Epoch:25,Loss:0.04291125014424324
Epoch:25,Loss:0.16618308424949646
Epoch:25,Loss:0.03831235319375992
Epoch:25,Loss:0.02442573755979538
Epoch:25,Loss:0.04232180491089821
Epoch:25,Loss:0.018541336059570312

# Evaluation

In [194]:
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.5).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')

Accuracy: 0.9844